import React, { FC } from "react";
import { Link } from "react-router-dom";
const Privacy: React.FC = () => {
  return (
    <div className="min-h-screen bg-gray-900 text-white p-8" style={{ backgroundColor: 'var(--c-bg-dark)', color: 'var(--c-fg-light)' }}>
      <div className="container mx-auto max-w-4xl">
        <h1 className="text-4xl font-bold mb-8">Privacy Policy</h1>
        <div className="bg-gray-800 p-6 rounded-lg shadow-lg leading-relaxed" style={{ backgroundColor: 'var(--c-surface)', borderRadius: 'var(--radius)' }}>
          <p className="mb-4" style={{ color: 'var(--c-fg-light)' }}>Effective Date: October 26, 2023</p>
          <p className="mb-4" style={{ color: 'var(--c-fg-muted)' }}>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <h2 className="text-2xl font-semibold mb-3" style={{ color: 'var(--c-primary)' }}>Interpretation and Definitions</h2>
          <h3 className="text-xl font-semibold mb-2" style={{ color: 'var(--c-fg-light)' }}>Interpretation</h3>
          <p className="mb-4" style={{ color: 'var(--c-fg-muted)' }}>
            The words of which the initial letter is capitalized have meanings defined under the following conditions.
            The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>
          <h3 className="text-xl font-semibold mb-2" style={{ color: 'var(--c-fg-light)' }}>Definitions</h3>
          <ul className="list-disc list-inside mb-4 space-y-2" style={{ color: 'var(--c-fg-muted)' }}>
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to SaaS Boilerplate Inc.</li>
            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><strong>Country</strong> refers to: United States</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the Website.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
            <li><strong>Website</strong> refers to SaaS Boilerplate, accessible from <Link to="/" className="underline" style={{ color: 'var(--c-primary)' }}>yourdomain.com</Link></li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>
          <h2 className="text-2xl font-semibold mb-3" style={{ color: 'var(--c-primary)' }}>Collecting and Using Your Personal Data</h2>
          <h3 className="text-xl font-semibold mb-2" style={{ color: 'var(--c-fg-light)' }}>Types of Data Collected</h3>
          <h4 className="text-lg font-medium mb-1" style={{ color: 'var(--c-fg-light)' }}>Personal Data</h4>
          <p className="mb-4" style={{ color: 'var(--c-fg-muted)' }}>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
          <ul className="list-disc list-inside mb-4 space-y-2" style={{ color: 'var(--c-fg-muted)' }}>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Usage Data</li>
          </ul>
          <h4 className="text-lg font-medium mb-1" style={{ color: 'var(--c-fg-light)' }}>Usage Data</h4>
          <p className="mb-4" style={{ color: 'var(--c-fg-muted)' }}>
            Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.'
          </p>
          <div className="mt-8 text-center">
            <Link
              to="/"
              className="text-gray-400 hover:text-gray-200 transition-colors duration-200"
              style={{ color: 'var(--c-fg-muted)' }}
            >
              Back to Home
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};
export default Privacy;